INSERT INTO hate_food (id, food, img_url) values (default , '파인애플피자', 'dummy');
INSERT INTO hate_food (id, food) values (default , '닭발');
INSERT INTO hate_food (id, food) values (default , '평양냉면');
INSERT INTO hate_food (id, food) values (default , '번데기');
INSERT INTO hate_food (id, food) values (default , '청국장');
INSERT INTO hate_food (id, food) values (default , '소 생간');
INSERT INTO hate_food (id, food) values (default , '돼지껍데기');
INSERT INTO hate_food (id, food) values (default , '홍어회');
INSERT INTO hate_food (id, food) values (default , '건포도');
INSERT INTO hate_food (id, food) values (default , '가지');
INSERT INTO hate_food (id, food) values (default , '오이');
INSERT INTO hate_food (id, food) values (default , '생굴');
INSERT INTO hate_food (id, food) values (default , '곱창');
INSERT INTO hate_food (id, food) values (default , '막창');
INSERT INTO hate_food (id, food) values (default , '대창');
INSERT INTO hate_food (id, food) values (default , '돼지 허파');
INSERT INTO hate_food (id, food) values (default , '고수');
INSERT INTO hate_food (id, food) values (default , '추어탕');
INSERT INTO hate_food (id, food) values (default , '산낙지');
INSERT INTO hate_food (id, food) values (default , '회');
INSERT INTO hate_food (id, food) values (default , '알탕');
INSERT INTO hate_food (id, food) values (default , '닭똥집');
INSERT INTO hate_food (id, food) values (default , '선지해장국');
INSERT INTO hate_food (id, food) values (default , '양고기');
INSERT INTO hate_food (id, food) values (default , '닭 퍽퍽살');
INSERT INTO hate_food (id, food) values (default , '녹차 아이스크림');
INSERT INTO hate_food (id, food) values (default , '양고기');
INSERT INTO hate_food (id, food) values (default , '육회');
